version: '3'

volumes:
  postgres-data:
  redis-data:

services:
  # PHP 7.3 (with Nginx)
  app:
    container_name: base-app
    build: ./devops/environments/development/dockerfiles/app
    volumes:
      - ./project:/var/www/app
    ports:
      - '80:8080'
    depends_on:
      - postgres
      - redis
      - worker

  # Front NodeJS
  front:
    container_name: base-front
    build: ./devops/environments/development/dockerfiles/front
    tty: true
    volumes:
      - ./project:/var/www/app

  # Postgres (11)
  postgres:
    container_name: base-postgres
    image: postgres:12.1-alpine
    command: postgres -c datestyle='iso, dmy'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpass
      - POSTGRES_DB=base

  # Worker
  worker:
    container_name: base-worker
    build: ./devops/environments/development/dockerfiles/worker
    volumes:
      - ./project:/var/www/app
    depends_on:
      - postgres
      - redis

  # Redis
  redis:
    container_name: base-redis
    image: redis:5.0.7-alpine
    volumes:
      - 'redis-data:/data'
    ports:
      - 6379:6379

  # Fake SMTP Server.
  mailhog:
    container_name: base-mailhog
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025' # Port 1025 => SMTP.
      - '8025:8025' # Port 8025 => Web dashboard (http://127.0.0.1:8025).
